### ISSUE TITLE
Overriding test class?

### ISSUE THREAD

**Issue by mlambley** [wolfsellers/module-enabledisabletfa#1]
https://github.com/wolfsellers/module-enabledisabletfa/blob/24e33ee0a64cdcd534b0051f1e9afa3c4c700045/etc/di.xml#L1-L4

If I'm not mistaken, it looks like you're overriding the class which allows legacy tests to run. I think the class you want to plugin is `Magento\TwoFactorAuth\Observer\ControllerActionPredispatch`

Or maybe even `Magento\TwoFactorAuth\Api\TfaSessionInterface` and just set `isGranted` to true.

**Comment by Rus0** [comment]
@mlambley I tried a preference for `Magento\TwoFactorAuth\Observer\ControllerActionPredispatch` after activating production mode, it wouldn't work. That class actually overrides `Magento\TwoFactorAuth\Observer\ControllerActionPredispatch`, If I only overrid the Observer Class, the Test Framework was throwing an error also.
